services:
  db:
    hostname: 127.0.0.1
    image: ankane/pgvector
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=ai4ba
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres